// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types.ts';

const SUPABASE_URL = "https://ctolvnqqdlhjpozqjsfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0b2x2bnFxZGxoanBvenFqc2Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODU0OTYsImV4cCI6MjA2ODY2MTQ5Nn0.kmnnHbBKN7wiBESC90MxVoJkEloQFGBkF3VYfOS2AfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});